#config_version=6
# modes/high_score/config/high_score.yaml

mode:
  priority: 500
  start_events: game_ending
  use_wait_queue: true

high_score:
  _overwrite: true
  enter_initials_timeout: 180s
  award_slide_display_time: 10s

  categories: !!omap
    - score:
        - GRAND CHAMPION
        - HIGH SCORE 1
        - HIGH SCORE 2
        - HIGH SCORE 3
        - HIGH SCORE 4

  defaults:
    score:
      - BWC: 1000000
      - APC: 500000
      - CLC: 300000
      - WFC: 200000
      - EYI: 20000

slide_player:
  _overwrite: true
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display: high_score_award_display

event_player:
  high_score_enter_initials:
    tl_high_score_entry_started

  high_score_award_display:
    tl_high_score_award_display