#config_version=6
# modes/attract/config/attract.yaml
# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.


mode_settings:
  selectable_items:
    - title
    - title2
  next_item_events: s_16_right_flipper_active, timer_attract_carousel_timer_complete
  previous_item_events: s_08_left_flipper_active

slide_player:
  mode_attract_started: attract

event_player:
  mode_attract_started: start_mode_attract_scores, start_mode_attract_credits
  mode_attract_will_stop: stop_mode_attract_scores, stop_mode_attract_credits

show_player:
  mode_attract_started:
    show_tv_staticbreath_1:
      loops: -1
      priority: 100
    show_tv_staticfast_1:
      loops: -1
      priority: 100
    show_fig8_attract_2:
      loops: -1
      speed: 1.0
      priority: 200
    # show_rightorbit_1:
    #   loops: -1
    #   priority: 200
    rainbow_pops_1:
      loops: -1
      priority: 300
    show_reel_1:
      loops: -1
      priority: 400
    show_multi_attract_1:
      loops: -1
      priority: 500
    show_modeinserts_sweep_green_1:
      loops: -1
      priority: 600
    show_vari_red_1:
      loops: -1
      priority: 700
    show_leftramp_attract_1:
      loops: -1
      speed: 1.0
      priority: 800
    show_shotgun_attract_1:
      loops: -1
      priority: 900
    show_inlaneinserts_attract_1:
      loops: -1
      speed: 2.0
      priority: 910
    show_tiltwarnings_attract_1:
      loops: -1
      speed: 5.0
      priority: 910
    show_gi_attract_1:
      loops: -1
      speed: 1.0
    # show_cab_test_1:
    #   loops: -1
    #   speed: 1.0
    show_light_bar_attract_1:
      loops: -1
      speed: 1.0



sound_player:
  mode_attract_started:
    tl-m-Hysteria-smallintro:
      bus: music
      loops: -1

  mode_attract_will_stop:
    tl-m-Hysteria-smallintro:
      action: stop


timers:
  attract_carousel_timer:
    end_value: 1
    tick_interval: 5s
    start_running: true
    control_events:
      - event: timer_attract_carousel_timer_complete
        action: restart
      - event: s_16_right_flipper_active
        action: restart
      - event: s_08_left_flipper_active
        action: restart
      - event: flipper_cradle
        action: stop
      - event: flipper_cradle_release
        action: restart
