#config_version=6
# modes/base/config/base.yaml

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

config:
  - base_points.yaml
  - varitarget.yaml
  - shots.yaml
  #- shot_groups.yaml
  #- shot_profiles.yaml
  #- consume_qualify.yaml

event_player:
  mode_base_started: BASE_YAML_LOADED

  s_03_service_enter_active: end_game

  manual_ball_search_requested:
    - start_manual_ball_search

  ball_started{current_player.ball==3}:
    - knights_of_cydonia_started


variable_player:
  mode_base_started:
    pf_multiplier:
      action: set
      int: 1

slide_player:
  mode_base_started:
    base_slide:
      priority: 300

sound_player:
  spinner_left_hit:
    spinner:
      bus: effects
      max_queue_time: 5ms

  ball_started{current_player.ball==1}:
    tl_m_hysteria_fullsong:
      bus: music
      loops: -1

  ball_started{current_player.ball==2}:
    tl_m_mapofprob_fullsong:
      bus: music
      loops: -1

  ball_started{current_player.ball==3}:
    tl_m_koc_fullsong:
      bus: music
      loops: -1

  spinner_right_hit:
    spinner:
      bus: effects
      max_queue_time: 40ms

show_player:
  knights_of_cydonia_started:
    show_koc_vocal_solo_pops_only:
    #show_koc_vocal_solo:
      loops: 1
      speed: 1.0
      priority: 99
      key: koc__vocal_solo



    show_muse_knights_cue_master:
      loops: 1
      speed: 1.0
      priority: 1
      key: koc_cue_master

    show_koc_rhythm_background_layer:
      loops: 1
      speed: 1.0
      priority: 30
      key: koc_rhythm_layer

    show_koc_bass_vu_layer:
      loops: 1
      speed: 1.0
      priority: 45
      key: koc_bass_layer

    show_koc_lead_guitar_layer:
      loops: 1
      speed: 1.0
      priority: 55
      key: koc_lead_layer

    show_koc_drum_macro_layer:
      loops: 1
      speed: 1.0
      priority: 70
      key: koc_drum_layer

    show_koc_vocal_cue_layer:
      loops: 1
      speed: 1.0
      priority: 85
      key: koc_vocal_layer

    # show_koc_final_survive_overlay:
    #   loops: 1
    #   speed: 1.0
    #   priority: 1500
    #   key: koc_final_survive_overlay


  s_38_star_rollover_bottom_active:
    show_rollover_bottom_hit_1:
      loops: 1
      speed: 1.0
      priority: 500
  
  s_39_star_rollover_top_active:
    show_rollover_top_hit_1:
      loops: 3
      speed: 1.0
      priority: 1500
  
  s_37_left_sling_active:
    show_sling_left_green_1:
      loops: 1
      speed: 2.0
      priority: 500
  
  s_34_right_sling_active:
    show_sling_right_green_1:
      loops: 1
      speed: 2.0
      priority: 500
  
  s_58_pop_bumper_left_active:
    show_pop_bumper_left_hit_1:
      loops: 1
      speed: 1.0
      priority: 500

  s_57_pop_bumper_center_active:
    show_pop_bumper_center_hit_1:
      loops: 1
      speed: 1.0
      priority: 500

  s_56_pop_bumper_right_active:
    show_pop_bumper_right_hit_1:
      loops: 1
      speed: 1.0
      priority: 500

  spinner_left_hit:
    show_left_spinner_white_strobe_1:
      loops: 4
      speed: 2.0
      priority: 500

  spinner_right_hit:
    show_right_spinner_white_strobe_1:
      loops: 4
      speed: 2.0
      priority: 500

  ball_started{current_player.ball==1}:
    show_muse_hysteria_radio_full:
      loops: 0
      speed: 1.0
      priority: 10
      key: hysteria_background

    show_floods_hysteria_bassline_1:
      loops: 0
      speed: 1.0
      priority: 200
      key: hysteria_cab

  ball_will_end:
    hysteria_background:
      action: stop
    hysteria_cab:
      action: stop
    koc_cue_master:
      action: stop
    koc_vocal_layer:
      action: stop
    koc_drum_layer:
      action: stop
    koc_bass_layer:
      action: stop
    koc_lead_layer:
      action: stop
    koc_rhythm_layer:
      action: stop
    koc_final_survive_overlay:
      action: stop
    # knights_master:
    #   action: stop

  ball_started{current_player.ball==2}:
    show_muse_mapofprob_radio_full:
      loops: 0
      speed: 1.0
      priority: 10

  # knights_of_cydonia_started:
  #   show_muse_knights_master:
  #     loops: 1
  #     speed: 1.0
  #     priority: 100
  #     key: knights_master

  # knights_intro_start:
  #   show_knights_intro:
  #     loops: 1
  #     speed: 1.0
  #     priority: 500

  # knights_build_1_start:
  #   show_knights_build_1:
  #     loops: 1
  #     speed: 1.0
  #     priority: 500

  # knights_main_riff_start:
  #   show_knights_main_riff:
  #     loops: 1
  #     speed: 1.0
  #     priority: 500

  # knights_verse_1_start:
  #   show_knights_verse_1:
  #     loops: 1
  #     speed: 1.0
  #     priority: 500

  # knights_build_2_start:
  #   show_knights_build_2:
  #     loops: 1
  #     speed: 1.0
  #     priority: 500

  # knights_take_me_alive_1_start:
  #   show_knights_take_me_alive_1:
  #     loops: 1
  #     speed: 1.0
  #     priority: 500

  # knights_gallop_start:
  #   show_knights_gallop:
  #     loops: 1
  #     speed: 1.0
  #     priority: 500

  # knights_build_3_start:
  #   show_knights_build_3:
  #     loops: 1
  #     speed: 1.0
  #     priority: 500

  # knights_take_me_alive_final_start:
  #   show_knights_take_me_alive_final:
  #     loops: 1
  #     speed: 1.0
  #     priority: 500

combo_switches:
  cab_arrows_ball_search:
    switches_1: s_19_cab_arrow_left
    switches_2: s_20_cab_arrow_right
    hold_time: 5s
    events_when_both: manual_ball_search_requested