#config_version=6
# modes/base/config/base.yaml
mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

config:
  - base_points.yaml
  - varitarget.yaml
  - shots.yaml
  #- shot_groups.yaml
 # - shot_profiles.yaml
  #- consume_qualify.yaml

event_player:
  mode_base_started: BASE_YAML_LOADED
  s_03_service_enter_active: end_game
  
  manual_ball_search_requested:
    - start_manual_ball_search

variable_player:
  mode_base_started:
    pf_multiplier:
      action: set
      int: 1

slide_player:
  mode_base_started: base_slide

sound_player:
  spinner_left_hit:
    spinner:
      bus: effects
      #mode: random
      max_queue_time: 5ms

  mode_base_started:
    tl_m_hysteria_fullsong:
      bus: music
      loops: -1

  spinner_right_hit:
    spinner:
      bus: effects
      #mode: random
      max_queue_time: 40ms

show_player:
  s_58_pop_bumper_left_active:
    show_pop_bumper_left_hit_1:
      loops: 1
      speed: 1.0
      priority: 500
  
  s_57_pop_bumper_center_active:
    show_pop_bumper_center_hit_1:
      loops: 1
      speed: 1.0
      priority: 500

  s_56_pop_bumper_right_active:
    show_pop_bumper_right_hit_1:
      loops: 1
      speed: 1.0
      priority: 500
  
  spinner_left_hit:
    show_left_spinner_white_strobe_1:
      loops: 1
      speed: 1.0
      priority: 100

  spinner_right_hit:
    show_right_spinner_white_strobe_1:
      loops: 1
      speed: 1.0
      priority: 100

  ball_started:
    show_muse_hysteria_radio_full:
      loops: 0
      speed: 1.0
      priority: 10
      key: hysteria_background
  
  ball_will_end:
    hysteria_background:
      action: stop


combo_switches:
  cab_arrows_ball_search:
    switches_1: s_19_cab_arrow_left
    switches_2: s_20_cab_arrow_right
    hold_time: 5s
    events_when_both: manual_ball_search_requested

