#config_version=6
# modes/base/config/base.yaml
mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

config:
  - base_points.yaml
  - varitarget.yaml
  - shots.yaml
  #- shot_groups.yaml
 # - shot_profiles.yaml
  #- consume_qualify.yaml

event_player:
  mode_base_started: BASE_YAML_LOADED
  s_03_service_enter_active: end_game

variable_player:
  mode_base_started:
    pf_multiplier:
      action: set
      int: 1

slide_player:
  mode_base_started: base_slide

sound_player:
  spinner_left_hit:
    spinner:
      bus: effects
      #mode: random
      max_queue_time: 5ms

  mode_base_started:
    tl_m_hysteria_fullsong:
      bus: music
      loops: -1

  spinner_right_hit:
    spinner:
      bus: effects
      #mode: random
      max_queue_time: 40ms
