#config_version=6
# modes/shotgun/config/shotgun.yaml

mode:
  start_events: mode_base_started
  stop_events: mode_base_stopped
  priority: 120

timers:
  top_lane_a_countdown_timer:
    start_value: 30
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: false
    control_events:
      - event: shotgun_lane_a_charged
        action: restart
      - event: shotgun_stop_all
        action: stop
      - event: shotgun_stop_all
        action: reset
      - event: mode_shotgun_stopping
        action: stop

  top_lane_b_countdown_timer:
    start_value: 30
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: false
    control_events:
      - event: shotgun_lane_b_charged
        action: restart
      - event: shotgun_stop_all
        action: stop
      - event: shotgun_stop_all
        action: reset
      - event: mode_shotgun_stopping
        action: stop

  fourbank_reset_check_timer:
    start_value: 0
    end_value: 1
    direction: up
    tick_interval: 250ms
    start_running: false
    control_events:
      - event: fourbank_reset_requested
        action: restart
      - event: shotgun_stop_all
        action: stop
      - event: mode_shotgun_stopping
        action: stop

  fourbank_reset_retry_timer:
    start_value: 0
    end_value: 1
    direction: up
    tick_interval: 1s
    start_running: false
    control_events:
      - event: fourbank_reset_failed
        action: restart
      - event: shotgun_stop_all
        action: stop
      - event: mode_shotgun_stopping
        action: stop

  fourbank_drop_2_trip_timer:
    start_value: 0
    end_value: 1
    direction: up
    tick_interval: 200ms
    start_running: false
    control_events:
      - event: fourbank_drop_1_tripped
        action: restart

  fourbank_drop_3_trip_timer:
    start_value: 0
    end_value: 1
    direction: up
    tick_interval: 200ms
    start_running: false
    control_events:
      - event: fourbank_drop_2_tripped
        action: restart

  threebank_drop_1_trip_timer:
    start_value: 0
    end_value: 1
    direction: up
    tick_interval: 200ms
    start_running: false
    control_events:
      - event: fourbank_drop_3_tripped
        action: restart

  threebank_drop_2_trip_timer:
    start_value: 0
    end_value: 1
    direction: up
    tick_interval: 200ms
    start_running: false
    control_events:
      - event: threebank_drop_1_tripped
        action: restart

  threebank_drop_3_trip_timer:
    start_value: 0
    end_value: 1
    direction: up
    tick_interval: 200ms
    start_running: false
    control_events:
      - event: threebank_drop_2_tripped
        action: restart

event_player:
  mode_shotgun_started:
    - shotgun_vars_reset
    - shotgun_all_lights_off

  s_62_top_lane_a_active:
    - shotgun_lane_a_charged

  s_61_top_lane_b_active:
    - shotgun_lane_b_charged

  shotgun_lane_a_charged{current_player.shotgun_lane_b_active == 1 and current_player.shotgun_qualified == 0}:
    - shotgun_qualified

  shotgun_lane_b_charged{current_player.shotgun_lane_a_active == 1 and current_player.shotgun_qualified == 0}:
    - shotgun_qualified

  shotgun_qualified{current_player.alien_first_achieved == 0}:
    - alien_first_started

  shotgun_qualified{current_player.alien_first_achieved == 1 and current_player.alien_second_achieved == 0}:
    - alien_second_started

  alien_first_started:
    - fourbank_reset_attempts_clear
    - fourbank_reset_request

  alien_second_started:
    - fourbank_reset_attempts_clear
    - fourbank_reset_request

  fourbank_reset_request:
    - fourbank_reset_requested

  timer_fourbank_reset_check_timer_complete{not device.switches.s_73_fourbank_drop_1.state and not device.switches.s_74_fourbank_drop_2.state and not device.switches.s_75_fourbank_drop_3.state and not device.switches.s_76_fourbank_drop_4.state}:
    - fourbank_reset_confirmed

  timer_fourbank_reset_check_timer_complete{device.switches.s_73_fourbank_drop_1.state or device.switches.s_74_fourbank_drop_2.state or device.switches.s_75_fourbank_drop_3.state or device.switches.s_76_fourbank_drop_4.state}:
    - fourbank_reset_failed

  timer_fourbank_reset_retry_timer_complete{current_player.fourbank_reset_attempts < 3}:
    - fourbank_reset_request

  timer_fourbank_reset_retry_timer_complete{current_player.fourbank_reset_attempts >= 3}:
    - fourbank_drop_4_only

  fourbank_reset_confirmed:
    - fourbank_drop_4_only

  fourbank_drop_4_only:
    - fourbank_drop_1_tripped

  timer_fourbank_drop_2_trip_timer_complete:
    - fourbank_drop_2_tripped

  timer_fourbank_drop_3_trip_timer_complete:
    - fourbank_drop_3_tripped

  timer_threebank_drop_1_trip_timer_complete:
    - threebank_drop_1_tripped

  timer_threebank_drop_2_trip_timer_complete:
    - threebank_drop_2_tripped

  timer_threebank_drop_3_trip_timer_complete:
    - threebank_drop_3_tripped

  threebank_drop_3_tripped{current_player.shotgun_lane_a_active == 1 or current_player.shotgun_lane_b_active == 1}:
    - shotgun_mode_active_started

  s_76_fourbank_drop_4_active{current_player.shotgun_mode_active == 1 and current_player.alien_first_achieved == 0}:
    - alien_first_hit

  s_76_fourbank_drop_4_active{current_player.shotgun_mode_active == 1 and current_player.alien_first_achieved == 1 and current_player.alien_second_achieved_part1 == 0 and current_player.alien_second_achieved == 0}:
    - alien_second_part1_hit

  s_76_fourbank_drop_4_active{current_player.shotgun_mode_active == 1 and current_player.alien_first_achieved == 1 and current_player.alien_second_achieved_part1 == 1 and current_player.alien_second_achieved == 0}:
    - alien_second_final_hit

  alien_second_part1_hit:
    - fourbank_reset_attempts_clear
    - fourbank_reset_request

  timer_top_lane_a_countdown_timer_complete:
    - shotgun_lane_a_expired

  timer_top_lane_b_countdown_timer_complete:
    - shotgun_lane_b_expired

  shotgun_lane_a_expired{current_player.shotgun_qualified == 1 and current_player.shotgun_lane_b_active == 0 and not device.switches.s_76_fourbank_drop_4.state}:
    - shotgun_failed

  shotgun_lane_b_expired{current_player.shotgun_qualified == 1 and current_player.shotgun_lane_a_active == 0 and not device.switches.s_76_fourbank_drop_4.state}:
    - shotgun_failed

  alien_first_hit:
    - shotgun_stop_all
    - shotgun_sequence_reset

  alien_second_final_hit:
    - shotgun_stop_all
    - shotgun_sequence_reset

  shotgun_failed:
    - shotgun_stop_all
    - shotgun_sequence_reset

variable_player:
  shotgun_vars_reset:
    shotgun_lane_a_active:
      action: set
      int: 0
    shotgun_lane_b_active:
      action: set
      int: 0
    shotgun_qualified:
      action: set
      int: 0
    shotgun_mode_active:
      action: set
      int: 0
    alien_first_achieved:
      action: set
      int: 0
    alien_second_started:
      action: set
      int: 0
    alien_second_achieved_part1:
      action: set
      int: 0
    alien_second_achieved:
      action: set
      int: 0
    fourbank_reset_request:
      action: set
      int: 0
    fourbank_reset_requested:
      action: set
      int: 0
    fourbank_reset_confirmed:
      action: set
      int: 0
    fourbank_reset_failed:
      action: set
      int: 0
    fourbank_reset_attempts:
      action: set
      int: 0

  shotgun_sequence_reset:
    shotgun_lane_a_active:
      action: set
      int: 0
    shotgun_lane_b_active:
      action: set
      int: 0
    shotgun_qualified:
      action: set
      int: 0
    shotgun_mode_active:
      action: set
      int: 0
    alien_second_started:
      action: set
      int: 0
    alien_second_achieved_part1:
      action: set
      int: 0
    fourbank_reset_request:
      action: set
      int: 0
    fourbank_reset_requested:
      action: set
      int: 0
    fourbank_reset_confirmed:
      action: set
      int: 0
    fourbank_reset_failed:
      action: set
      int: 0
    fourbank_reset_attempts:
      action: set
      int: 0

  shotgun_lane_a_charged:
    shotgun_lane_a_active:
      action: set
      int: 1

  shotgun_lane_b_charged:
    shotgun_lane_b_active:
      action: set
      int: 1

  shotgun_qualified:
    shotgun_qualified:
      action: set
      int: 1

  alien_first_started:
    shotgun_mode_active:
      action: set
      int: 0

  alien_second_started:
    alien_second_started:
      action: set
      int: 1
    alien_second_achieved_part1:
      action: set
      int: 0
    shotgun_mode_active:
      action: set
      int: 0

  shotgun_mode_active_started:
    shotgun_mode_active:
      action: set
      int: 1

  fourbank_reset_attempts_clear:
    fourbank_reset_attempts:
      action: set
      int: 0
    fourbank_reset_confirmed:
      action: set
      int: 0
    fourbank_reset_failed:
      action: set
      int: 0

  fourbank_reset_request:
    fourbank_reset_request:
      action: set
      int: 1
    fourbank_reset_requested:
      action: set
      int: 0
    fourbank_reset_confirmed:
      action: set
      int: 0
    fourbank_reset_failed:
      action: set
      int: 0
    shotgun_mode_active:
      action: set
      int: 0
    fourbank_reset_attempts:
      action: add
      int: 1

  fourbank_reset_requested:
    fourbank_reset_requested:
      action: set
      int: 1

  fourbank_reset_confirmed:
    fourbank_reset_confirmed:
      action: set
      int: 1
    fourbank_reset_request:
      action: set
      int: 0
    fourbank_reset_requested:
      action: set
      int: 0
    fourbank_reset_failed:
      action: set
      int: 0

  fourbank_reset_failed:
    fourbank_reset_failed:
      action: set
      int: 1
    fourbank_reset_request:
      action: set
      int: 0
    fourbank_reset_requested:
      action: set
      int: 0

  shotgun_lane_a_expired:
    shotgun_lane_a_active:
      action: set
      int: 0

  shotgun_lane_b_expired:
    shotgun_lane_b_active:
      action: set
      int: 0

  alien_first_hit:
    score: 500000
    alien_first_achieved:
      action: set
      int: 1
    shotgun_mode_active:
      action: set
      int: 0

  alien_second_part1_hit:
    score: 500000
    alien_second_achieved_part1:
      action: set
      int: 1
    shotgun_mode_active:
      action: set
      int: 0

  alien_second_final_hit:
    score: 2000000
    alien_second_achieved:
      action: set
      int: 1
    shotgun_mode_active:
      action: set
      int: 0

  shotgun_failed:
    shotgun_lane_a_active:
      action: set
      int: 0
    shotgun_lane_b_active:
      action: set
      int: 0
    shotgun_qualified:
      action: set
      int: 0
    shotgun_mode_active:
      action: set
      int: 0

coil_player:
  fourbank_reset_request:
    c_40_fourbank_drop_reset:
      action: pulse

  fourbank_drop_4_only:
    c_33_fourbank_drop_1_trip:
      action: pulse

  timer_fourbank_drop_2_trip_timer_complete:
    c_34_fourbank_drop_2_trip:
      action: pulse

  timer_fourbank_drop_3_trip_timer_complete:
    c_35_fourbank_drop_3_trip:
      action: pulse

  timer_threebank_drop_1_trip_timer_complete:
    c_37_threebank_drop_1_trip:
      action: pulse

  timer_threebank_drop_2_trip_timer_complete:
    c_38_threebank_drop_2_trip:
      action: pulse

  timer_threebank_drop_3_trip_timer_complete:
    c_39_threebank_drop_3_trip:
      action: pulse

  shotgun_failed:
    c_36_fourbank_drop_4_trip:
      action: pulse

light_player:
  shotgun_all_lights_off:
    l_pf1_2_31: off
    l_pf1_2_30: off
    l_pf1_2_29: off
    l_pf1_2_24: off
    l_pf1_2_25: off
    l_pf1_2_26: off
    l_pf1_2_27: off
    l_pf1_2_28: off

  shotgun_stop_all:
    l_pf1_2_31: off
    l_pf1_2_30: off
    l_pf1_2_29: off
    l_pf1_2_24: off
    l_pf1_2_25: off
    l_pf1_2_26: off

  shotgun_lane_a_charged:
    l_pf1_2_31: '00ff00'
    l_pf1_2_30: '00ff00'
    l_pf1_2_29: '00ff00'

  shotgun_lane_b_charged:
    l_pf1_2_24: '00ff00'
    l_pf1_2_25: '00ff00'
    l_pf1_2_26: '00ff00'

  timer_top_lane_a_countdown_timer_tick{ticks_remaining == 19}:
    l_pf1_2_31: off

  timer_top_lane_a_countdown_timer_tick{ticks_remaining == 9}:
    l_pf1_2_31: off
    l_pf1_2_30: off

  timer_top_lane_b_countdown_timer_tick{ticks_remaining == 19}:
    l_pf1_2_24: off

  timer_top_lane_b_countdown_timer_tick{ticks_remaining == 9}:
    l_pf1_2_24: off
    l_pf1_2_25: off

  timer_top_lane_a_countdown_timer_complete:
    l_pf1_2_31: off
    l_pf1_2_30: off
    l_pf1_2_29: off

  timer_top_lane_b_countdown_timer_complete:
    l_pf1_2_24: off
    l_pf1_2_25: off
    l_pf1_2_26: off

shows:
  shotgun_flash_2hz:
    - duration: 250ms
      lights:
        (led1): '00ff00'
        (led2): '00ff00'
    - duration: 250ms
      lights:
        (led1): off
        (led2): off

  shotgun_flash_6hz:
    - duration: 83ms
      lights:
        (led): '00ff00'
    - duration: 83ms
      lights:
        (led): off

  shotgun_red_breathe:
    - duration: 700ms
      lights:
        (led): 'ff0000'
    - duration: 700ms
      lights:
        (led): '220000'

show_player:
  shotgun_lane_a_charged:
    shotgun_lane_a_2hz:
      action: stop
    shotgun_lane_a_6hz:
      action: stop

  shotgun_lane_b_charged:
    shotgun_lane_b_2hz:
      action: stop
    shotgun_lane_b_6hz:
      action: stop

  timer_top_lane_a_countdown_timer_tick{ticks_remaining == 19}:
    shotgun_flash_2hz:
      key: shotgun_lane_a_2hz
      loops: -1
      show_tokens:
        led1: l_pf1_2_30
        led2: l_pf1_2_29

  timer_top_lane_a_countdown_timer_tick{ticks_remaining == 9}:
    shotgun_lane_a_2hz:
      action: stop
    shotgun_flash_6hz:
      key: shotgun_lane_a_6hz
      loops: -1
      show_tokens:
        led: l_pf1_2_29

  timer_top_lane_b_countdown_timer_tick{ticks_remaining == 19}:
    shotgun_flash_2hz:
      key: shotgun_lane_b_2hz
      loops: -1
      show_tokens:
        led1: l_pf1_2_25
        led2: l_pf1_2_26

  timer_top_lane_b_countdown_timer_tick{ticks_remaining == 9}:
    shotgun_lane_b_2hz:
      action: stop
    shotgun_flash_6hz:
      key: shotgun_lane_b_6hz
      loops: -1
      show_tokens:
        led: l_pf1_2_26

  timer_top_lane_a_countdown_timer_complete:
    shotgun_lane_a_2hz:
      action: stop
    shotgun_lane_a_6hz:
      action: stop

  timer_top_lane_b_countdown_timer_complete:
    shotgun_lane_b_2hz:
      action: stop
    shotgun_lane_b_6hz:
      action: stop

  shotgun_stop_all:
    shotgun_lane_a_2hz:
      action: stop
    shotgun_lane_a_6hz:
      action: stop
    shotgun_lane_b_2hz:
      action: stop
    shotgun_lane_b_6hz:
      action: stop

  alien_first_hit:
    shotgun_red_breathe:
      key: alien_first_breathe
      loops: -1
      show_tokens:
        led: l_pf1_2_28

  alien_second_final_hit:
    shotgun_red_breathe:
      key: alien_second_breathe
      loops: -1
      show_tokens:
        led: l_pf1_2_27
