#config_version=6

switches: 
  # define cabinet switches
  s_flipper_left:
    number:
    tags: left_flipper
  s_flipper_right:
    number:
    tags: right_flipper
  
  #trough switches
  s_trough_1:
    number:
  s_trough_2:
    number:
  s_trough_3:
    number:
  s_plunger_lane:
    number:

  # define droptarget 7-bank switches
  s_droptarget_1:
    number:
    tags: droptarget_1
  s_droptarget_2:
    number:
    #tags: droptarget_2
  s_droptarget_3:
    number:
    #tags: droptarget_3
  s_droptarget_4:
    number:
    #tags: droptarget_4
  s_droptarget_5:
    number:
    #tags: droptarget_5
  s_droptarget_6:
    number:
    #tags: droptarget_6
  s_droptarget_7:
    number:
    #tags: droptarget_7

  # define standup 6-bank switches
  s_standup6bank_1:
    number:
    #tags: standup6bank_1
  s_standup6bank_2:
    number:
    #tags: standup6bank_2
  s_standup6bank_3:
    number:
    #tags: standup6bank_3
  s_standup6bank_4:
    number:
    #tags: standup6bank_4
  s_standup6bank_5:
    number:
    #tags: standup6bank_5
  s_standup6bank_6:
    number:
    #tags: standup6bank_6