#config_version=6
# config/seq_shots.yaml

sequence_shots:

  # Clean Left Loop
  ssh_clean_left_loop:
    switch_sequence: s_32_right_inlane, s_71_spinner_left, s_60_top_lane_c
    sequence_timeout: 3s

  # Clean Right Loop
  ssh_clean_right_loop:
    switch_sequence: s_35_left_inlane, s_60_top_lane_c, s_71_spinner_left
    sequence_timeout: 3s

  # Clean Right Spinner
  ssh_clean_right_spinner:
    switch_sequence: s_35_left_inlane, s_38_star_rollover_bottom, s_39_star_rollover_top, s_44_spinner_right
    sequence_timeout: 3s


  # COMBOS
  ssh_posts_v:
    switch_sequence: s_40_stand_up_target_5, s_41_stand_up_target_6, s_43_stand_up_target_4
    sequence_timeout: 5s




# shots:

#   shot_impossible:
#     switches: s_42_stand_up_target_1

#   shot_dt_1:
#     switches: s_73_fourbank_drop_1

#   shot_dt_2:
#     switches: s_74_fourbank_drop_2

#   shot_dt_3:
#     switches: s_75_fourbank_drop_3

#   shot_dt_4:
#     switches: s_76_fourbank_drop_4

#   shot_dt_5:
#     switches: s_77_threebank_drop_1

#   shot_dt_6:
#     switches: s_78_threebank_drop_2

#   shot_dt_7:
#     switches: s_79_threebank_drop_3

#   shot_sut_1:
#     switches: s_82_stand_up_target_bank_1

#   shot_sut_2:
#     switches: s_83_stand_up_target_bank_2

#   shot_sut_3:
#     switches: s_84_stand_up_target_bank_3

#   shot_sut_4:
#     switches: s_85_stand_up_target_bank_4

#   shot_sut_5:
#     switches: s_86_stand_up_target_bank_5

#   shot_sut_6:
#     switches: s_87_stand_up_target_bank_6

#   shot_sut_green:
#     switches: s_82_stand_up_target_bank_1, s_87_stand_up_target_bank_6

#   shot_sut_blue:
#     switches: s_83_stand_up_target_bank_2, s_86_stand_up_target_bank_5

#   shot_sut_red:
#     switches: s_84_stand_up_target_bank_3, s_85_stand_up_target_bank_4

#   shot_slingshot_l:
#     switches: s_37_left_sling

#   shot_slingshot_r:
#     switches: s_34_right_sling
  
#   shot_rollover_bottom:
#     switches: s_38_star_rollover_bottom

#   shot_rollover_top:
#     switches: s_39_star_rollover_top
