#config_version=6
# STARs Mode scoring overlay
# 10x total on spinner hits only = base 10,000 + 90,000 bonus

variable_player:

  s_71_spinner_left_active{current_player.stars_10x_active == 1}:
    score: 90000

  s_44_spinner_right_active{current_player.stars_10x_active == 1}:
    score: 90000